// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddoeydxyekjfrvgegfgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkb2V5ZHh5ZWtqZnJ2Z2VnZmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODI4NDgsImV4cCI6MjA3MzY1ODg0OH0.tJvIKT-gvR4aMmDldVwDs6uGcd7UUdnM3BoCVEXEzyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});